server:
  port: 8083
Spring:
  application:
    name: customer-core
  redis:
    host: localhost
    port: 6379
  data:
    redis:
      repositories:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


